/**
 * The `parliament:report` job: what the database holds against what the
 * source should give, and every member with a gap. Written to
 * docs/reports/parliament-<date>.md so it can be reviewed and committed.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { and, eq, isNull, sql } from 'drizzle-orm';
import { schema } from '@durbin/db';
import type { Db } from './parliament-core';

const { committees, constituencies, memberTerms, members, notices, parliaments, sittings, noticeMembers } = schema;

export async function buildReport(db: Db, parliamentNumber = 13): Promise<string> {
  const [parl] = await db.select().from(parliaments).where(eq(parliaments.number, parliamentNumber));
  if (!parl) throw new Error(`parliament ${parliamentNumber} is not seeded`);

  const sitting = await db
    .select({
      id: members.id,
      nameBn: members.nameBn,
      externalId: members.sourceExternalId,
      photoUrl: members.photoUrl,
      photoSourceUrl: members.photoSourceUrl,
      email: members.officialEmail,
      profession: members.professionBn,
      dob: members.dateOfBirth,
      seat: memberTerms.seatLabelBn,
      constituencyId: memberTerms.constituencyId,
      partyId: memberTerms.partyId,
    })
    .from(members)
    .innerJoin(memberTerms, and(eq(memberTerms.memberId, members.id), eq(memberTerms.parliamentId, parl.id), eq(memberTerms.role, 'MP')));

  const seats = await db
    .select({ id: constituencies.id, number: constituencies.number, nameBn: constituencies.nameBn, reserved: constituencies.isReservedWomen })
    .from(constituencies)
    .where(eq(constituencies.parliamentId, parl.id));
  const held = new Set(sitting.map((s) => s.constituencyId).filter((x): x is number => x !== null));
  const vacant = seats.filter((s) => !held.has(s.id));

  const officers = await db
    .select({ role: memberTerms.role, nameBn: members.nameBn })
    .from(memberTerms)
    .innerJoin(members, eq(members.id, memberTerms.memberId))
    .where(and(eq(memberTerms.parliamentId, parl.id), sql`${memberTerms.role} <> 'MP'`));

  const [committeeRow] = await db
    .select({ total: sql<number>`count(*)::int`, current: sql<number>`count(*) filter (where roster_current)::int` })
    .from(committees)
    .where(eq(committees.parliamentId, parl.id));
  const [sittingRow] = await db.select({ n: sql<number>`count(*)::int` }).from(sittings);
  const [noticeRow] = await db.select({ n: sql<number>`count(*)::int` }).from(notices);
  const [noticeMemberRow] = await db.select({ n: sql<number>`count(distinct member_id)::int` }).from(noticeMembers);
  const [earlierRow] = await db
    .select({ n: sql<number>`count(distinct member_id)::int` })
    .from(memberTerms)
    .where(and(sql`${memberTerms.parliamentId} <> ${parl.id}`, eq(memberTerms.role, 'MP')));

  const missing = (pred: (s: (typeof sitting)[number]) => boolean) => sitting.filter(pred);
  const noPhoto = missing((s) => !s.photoUrl);
  const noPhotoSource = missing((s) => !s.photoSourceUrl);
  const noEmail = missing((s) => !s.email);
  const noProfession = missing((s) => !s.profession);
  const noDob = missing((s) => !s.dob);
  const noParty = missing((s) => s.partyId === null);
  const list = (rows: typeof sitting) => (rows.length ? rows.map((s) => `- ${s.nameBn} · ${s.seat ?? 'আসন নেই'} (${s.externalId})`).join('\n') : '- none');

  const today = new Date().toISOString().slice(0, 10);
  return `# Parliament data report — ${today}

Source: parliament.gov.bd, parliament ${parliamentNumber}. Generated by \`pnpm worker parliament:report\`.

## Counts

| | |
|---|---|
| Sitting members in database | ${sitting.length} |
| Seats in the election set | ${seats.length} (${seats.filter((s) => !s.reserved).length} territorial + ${seats.filter((s) => s.reserved).length} reserved) |
| Seats with no sitting member | ${vacant.length} |
| Officers recorded | ${officers.length} |
| Committees | ${committeeRow?.total ?? 0} (${committeeRow?.current ?? 0} with a current roster) |
| Sittings with an order of the day | ${sittingRow?.n ?? 0} |
| Notices kept | ${noticeRow?.n ?? 0} (about ${noticeMemberRow?.n ?? 0} members) |
| Members with an earlier term on record | ${earlierRow?.n ?? 0} |

## Seats with no sitting member

${vacant.length ? vacant.map((v) => `- ${v.nameBn} (seat ${v.number}${v.reserved ? ', reserved' : ''})`).join('\n') : '- none'}

## Officers

${officers.length ? officers.map((o) => `- ${o.role}: ${o.nameBn}`).join('\n') : '- none matched'}

## Members with gaps

### No stored photo (${noPhoto.length})
${list(noPhoto)}

### No photo in the source at all (${noPhotoSource.length})
${list(noPhotoSource)}

### No official email (${noEmail.length})
${list(noEmail)}

### No profession (${noProfession.length})
${list(noProfession)}

### No date of birth (${noDob.length})
${list(noDob)}

### No party (${noParty.length})
${list(noParty)}
`;
}

export async function runReport(db: Db): Promise<{ itemsFound: number; itemsNew: number; path: string }> {
  const md = await buildReport(db);
  const dir = resolve(import.meta.dirname, '../../../docs/reports');
  await mkdir(dir, { recursive: true });
  const path = resolve(dir, `parliament-${new Date().toISOString().slice(0, 10)}.md`);
  await writeFile(path, md, 'utf8');
  process.stdout.write(`  report written: ${path}\n`);
  return { itemsFound: 1, itemsNew: 1, path };
}
